name: Docker Image CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labes) for Docker Web
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ secrets.DOCKER_USER }}/animeplex-web
        
    - name: Build the Docker image Web
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/web/DockerfileArm32v7
        push: true
        tags: ${{ steps.meta.outputs.tags }}-arm
        
    - name: Extract metadata (tags, labes) for Docker Api
      id: meta1
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ secrets.DOCKER_USER }}/animeplex-api
        
    - name: Build the Docker image Api
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/Cesxhin.AnimeSaturn/Cesxhin.AnimeSaturn.Api/DockerfileArm32v7
        push: true
        tags: ${{ steps.meta1.outputs.tags }}-arm

    - name: Extract metadata (tags, labes) for Docker DownloadService
      id: meta2
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ secrets.DOCKER_USER }}/animeplex-downloadservice
        
    - name: Build the Docker image DownloadService
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/Cesxhin.AnimeSaturn/Cesxhin.AnimeSaturn.DownloadService/DockerfileArm32v7
        push: true
        tags: ${{ steps.meta2.outputs.tags }}-arm

    - name: Extract metadata (tags, labes) for Docker UpdateService
      id: meta3
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ secrets.DOCKER_USER }}/animeplex-updateservice
        
    - name: Build the Docker image UpdateService
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/Cesxhin.AnimeSaturn/Cesxhin.AnimeSaturn.UpdateService/DockerfileArm32v7
        push: true
        tags: ${{ steps.meta3.outputs.tags }}-arm

    - name: Build the Docker image DownloadService
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/Cesxhin.AnimeSaturn/Cesxhin.AnimeSaturn.DownloadService/DockerfileArm32v7
        push: true
        tags: ${{ steps.meta2.outputs.tags }}-arm

    - name: Extract metadata (tags, labes) for Docker UpgradeService
      id: meta4
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ secrets.DOCKER_USER }}/animeplex-upgradeservice
        
    - name: Build the Docker image UpgradeService
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/Cesxhin.AnimeSaturn/Cesxhin.AnimeSaturn.UpgradeService/DockerfileArm32v7
        push: true
        tags: ${{ steps.meta4.outputs.tags }}-arm

    - name: Extract metadata (tags, labes) for Docker NotifyService
      id: meta5
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ secrets.DOCKER_USER }}/animeplex-notifyservice
        
    - name: Build the Docker image NotifyService
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/Cesxhin.AnimeSaturn/Cesxhin.AnimeSaturn.NotifyService/DockerfileArm32v7
        push: true
        tags: ${{ steps.meta5.outputs.tags }}-arm
